// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: demogrpc/item_like.proto

package demo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ItemLikeService_GetItemLikes_FullMethodName = "/demo.ItemLikeService/GetItemLikes"
)

// ItemLikeServiceClient is the client API for ItemLikeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ItemLikeServiceClient interface {
	GetItemLikes(ctx context.Context, in *GetItemLikeReq, opts ...grpc.CallOption) (*ItemLikesResp, error)
}

type itemLikeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewItemLikeServiceClient(cc grpc.ClientConnInterface) ItemLikeServiceClient {
	return &itemLikeServiceClient{cc}
}

func (c *itemLikeServiceClient) GetItemLikes(ctx context.Context, in *GetItemLikeReq, opts ...grpc.CallOption) (*ItemLikesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemLikesResp)
	err := c.cc.Invoke(ctx, ItemLikeService_GetItemLikes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemLikeServiceServer is the server API for ItemLikeService service.
// All implementations should embed UnimplementedItemLikeServiceServer
// for forward compatibility.
type ItemLikeServiceServer interface {
	GetItemLikes(context.Context, *GetItemLikeReq) (*ItemLikesResp, error)
}

// UnimplementedItemLikeServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedItemLikeServiceServer struct{}

func (UnimplementedItemLikeServiceServer) GetItemLikes(context.Context, *GetItemLikeReq) (*ItemLikesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemLikes not implemented")
}
func (UnimplementedItemLikeServiceServer) testEmbeddedByValue() {}

// UnsafeItemLikeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ItemLikeServiceServer will
// result in compilation errors.
type UnsafeItemLikeServiceServer interface {
	mustEmbedUnimplementedItemLikeServiceServer()
}

func RegisterItemLikeServiceServer(s grpc.ServiceRegistrar, srv ItemLikeServiceServer) {
	// If the following call pancis, it indicates UnimplementedItemLikeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ItemLikeService_ServiceDesc, srv)
}

func _ItemLikeService_GetItemLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemLikeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemLikeServiceServer).GetItemLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemLikeService_GetItemLikes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemLikeServiceServer).GetItemLikes(ctx, req.(*GetItemLikeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ItemLikeService_ServiceDesc is the grpc.ServiceDesc for ItemLikeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ItemLikeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "demo.ItemLikeService",
	HandlerType: (*ItemLikeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetItemLikes",
			Handler:    _ItemLikeService_GetItemLikes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demogrpc/item_like.proto",
}
